export const CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTquwEKsenrjJNqWkqjIYxjQA-37xqwG6jdhWU76_nqUOh9ejn_WKrbdpJNIq8VUTpOZ07LoFG4EFN_/pub?output=csv";
export const GAS_API_URL = "https://script.google.com/macros/s/AKfycbxANanQakAzjD8csDMcBFvD1ndEJi5OTNsBM9klRi6uLdDrjDWWq9jFcVJjGyEBWVxUMg/exec";
export const TOTAL_DAYS = 98;

export const ownerClassMap = {
  "設計專案": { tag: "owner-design", bar: "bar-design", hex: "#0284c7" },
  "土開": { tag: "owner-land", bar: "bar-land", hex: "#d97706" },
  "行銷/企劃": { tag: "owner-marketing", bar: "bar-marketing", hex: "#e11d48" },
  "客服": { tag: "owner-service", bar: "bar-service", hex: "#16a34a" },
  "顧問群(BIM)": { tag: "owner-bim", bar: "bar-bim", hex: "#9333ea" },
  "建築師": { tag: "owner-architect", bar: "bar-architect", hex: "#0d9488" },
  "結構技師": { tag: "owner-structure", bar: "bar-structure", hex: "#4f46e5" },
  "機電技師": { tag: "owner-mep", bar: "bar-mep", hex: "#ea580c" }
};

export const fallbackData = [
  { id: "T01", name: "00. 設計專案說明會", section: "階段 1：專案啟動與設計條件", owner: "設計專案", start: 0, end: 0, duration: 0, type: "milestone", deps: "-", deliverable: "全程營運列控表", actualFinish: "2026-08-01", delayDays: 0 },
  { id: "T01", name: "00. 設計專案說明會", section: "階段 1：專案啟動與設計條件", owner: "土開", start: 0, end: 0, duration: 0, type: "milestone", deps: "-", deliverable: "面積法規分析表", actualFinish: "2026-08-01", delayDays: 0 },
  { id: "T01", name: "00. 設計專案說明會", section: "階段 1：專案啟動與設計條件", owner: "土開", start: 0, end: 0, duration: 0, type: "milestone", deps: "-", deliverable: "建材設備表", actualFinish: "2026-08-01", delayDays: 0 },
  { id: "T02", name: "市場總經、客層策略與競品分析", section: "階段 2：市場定位與營運審查", owner: "行銷/企劃", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "區域行情表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T02", name: "市場總經、客層策略與競品分析", section: "階段 2：市場定位與營運審查", owner: "行銷/企劃", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "競品個案總表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T02", name: "市場總經、客層策略與競品分析", section: "階段 2：市場定位與營運審查", owner: "行銷/企劃", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "房坪統計表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T02", name: "市場總經、客層策略與競品分析", section: "階段 2：市場定位與營運審查", owner: "行銷/企劃", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "建材設備表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T03", name: "物管編制、維運回饋與管理費核算", section: "階段 2：市場定位與營運審查", owner: "客服", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "物管營運預算表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T03", name: "物管編制、維運回饋與管理費核算", section: "階段 2：市場定位與營運審查", owner: "客服", start: 0, end: 7, duration: 7, type: "task", deps: "T01", deliverable: "管理費核算表", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T04", name: "01. 跨部門聯合會議 (市場與營運)", section: "階段 2：市場定位與營運審查", owner: "行銷/企劃", start: 7, end: 7, duration: 0, type: "milestone", deps: "T02, T03", deliverable: "市場客層定位報告", actualFinish: "2026-08-08", delayDays: 0 },
  { id: "T04", name: "01. 跨部門聯合會議 (市場與營運)", section: "階段 2：市場定位與營運審查", owner: "客服", start: 7, end: 7, duration: 0, type: "milestone", deps: "T02, T03", deliverable: "營運物管預算確認", actualFinish: "2026-08-20", delayDays: 12 },
  { id: "T05", name: "量體剛性指標檢討與微氣候模擬", section: "階段 3：規劃設計與工程深化", owner: "設計專案", start: 7, end: 14, duration: 7, type: "task", deps: "T04", deliverable: "設計剛性需求表", actualFinish: "", delayDays: null },
  { id: "T05", name: "量體剛性指標檢討與微氣候模擬", section: "階段 3：規劃設計與工程深化", owner: "顧問群(BIM)", start: 7, end: 14, duration: 7, type: "task", deps: "T04", deliverable: "微氣候日照風場模擬報告", actualFinish: "", delayDays: null },
  { id: "T06", name: "造價成本設定與敏感度差異分析", section: "階段 3：規劃設計與工程深化", owner: "設計專案", start: 7, end: 14, duration: 7, type: "task", deps: "T04", deliverable: "單坪造價分級區間表", actualFinish: "", delayDays: null },
  { id: "T06", name: "造價成本設定與敏感度差異分析", section: "階段 3：規劃設計與工程深化", owner: "設計專案", start: 7, end: 14, duration: 7, type: "task", deps: "T04", deliverable: "工項成本設定表", actualFinish: "", delayDays: null },
  { id: "T06", name: "造價成本設定與敏感度差異分析", section: "階段 3：規劃設計與工程深化", owner: "設計專案", start: 7, end: 14, duration: 7, type: "task", deps: "T04", deliverable: "敏感度分析表", actualFinish: "", delayDays: null },
  { id: "T07", name: "02. 建築設計 (第一次)", section: "階段 3：規劃設計與工程深化", owner: "設計專案", start: 14, end: 14, duration: 0, type: "milestone", deps: "T05, T06", deliverable: "剛性需求及造價分級確認", actualFinish: "", delayDays: null },
  { id: "T08", name: "基地法規分析與量體規模方案模擬", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 14, end: 28, duration: 14, type: "task", deps: "T07", deliverable: "配置方案與量體分析", actualFinish: "", delayDays: null },
  { id: "T08", name: "基地法規分析與量體規模方案模擬", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 14, end: 28, duration: 14, type: "task", deps: "T07", deliverable: "房坪配比表", actualFinish: "", delayDays: null },
  { id: "T08", name: "基地法規分析與量體規模方案模擬", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 14, end: 28, duration: 14, type: "task", deps: "T07", deliverable: "平面設計標準表", actualFinish: "", delayDays: null },
  { id: "T09", name: "03. 建築設計 (第二次)", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 28, end: 28, duration: 0, type: "milestone", deps: "T08", deliverable: "初版標準層平面圖", actualFinish: "", delayDays: null },
  { id: "T09", name: "03. 建築設計 (第二次)", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 28, end: 28, duration: 0, type: "milestone", deps: "T08", deliverable: "初版地下室平面圖", actualFinish: "", delayDays: null },
  { id: "T10", name: "地質分析、結構框架與耐震標章檢討", section: "階段 3：規劃設計與工程深化", owner: "結構技師", start: 28, end: 35, duration: 7, type: "task", deps: "T09", deliverable: "結構系統概要說明書", actualFinish: "", delayDays: null },
  { id: "T10", name: "地質分析、結構框架與耐震標章檢討", section: "階段 3：規劃設計與工程深化", owner: "結構技師", start: 28, end: 35, duration: 7, type: "task", deps: "T09", deliverable: "耐震評估報告", actualFinish: "", delayDays: null },
  { id: "T11", name: "04. 結構工程設計", section: "階段 3：規劃設計與工程深化", owner: "結構技師", start: 35, end: 35, duration: 0, type: "milestone", deps: "T10", deliverable: "結構系統與材料強度定案", actualFinish: "", delayDays: null },
  { id: "T12", name: "系統架構規劃與五大管線/障礙物遷移套繪", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 28, end: 42, duration: 14, type: "task", deps: "T09", deliverable: "機電系統升位圖", actualFinish: "", delayDays: null },
  { id: "T12", name: "系統架構規劃與五大管線/障礙物遷移套繪", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 28, end: 42, duration: 14, type: "task", deps: "T09", deliverable: "五大管線現況調查套繪圖", actualFinish: "", delayDays: null },
  { id: "T13", name: "05. 機電工程設計 (第一次)", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 42, end: 42, duration: 0, type: "milestone", deps: "T12", deliverable: "機電系統架構定案", actualFinish: "", delayDays: null },
  { id: "T14", name: "單元戶房型傢配優化與公設動線配置", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 28, end: 49, duration: 21, type: "task", deps: "T09, T04", deliverable: "深化房型傢配圖", actualFinish: "", delayDays: null },
  { id: "T14", name: "單元戶房型傢配優化與公設動線配置", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 28, end: 49, duration: 21, type: "task", deps: "T09, T04", deliverable: "地下室第二門廳動線圖", actualFinish: "", delayDays: null },
  { id: "T15", name: "06. 建築設計 (第三次)", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 49, end: 49, duration: 0, type: "milestone", deps: "T14", deliverable: "單元戶格局及小公動線定案", actualFinish: "", delayDays: null },
  { id: "T16", name: "機房空間型化、幹管高程與穿樑開孔檢討", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 42, end: 56, duration: 14, type: "task", deps: "T13, T11", deliverable: "機電空間需求表", actualFinish: "", delayDays: null },
  { id: "T16", name: "機房空間型化、幹管高程與穿樑開孔檢討", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 42, end: 56, duration: 14, type: "task", deps: "T13, T11", deliverable: "穿樑套管圖", actualFinish: "", delayDays: null },
  { id: "T16", name: "機房空間型化、幹管高程與穿樑開孔檢討", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 42, end: 56, duration: 14, type: "task", deps: "T13, T11", deliverable: "機電工程規劃檢核表", actualFinish: "", delayDays: null },
  { id: "T17", name: "07. 機電工程設計 (第二次)", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 56, end: 56, duration: 0, type: "milestone", deps: "T16", deliverable: "管道間尺度與穿樑預留確認", actualFinish: "", delayDays: null },
  { id: "T18", name: "公設建材選用與建築裝修粉刷規格定案", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 49, end: 63, duration: 14, type: "task", deps: "T15", deliverable: "公設建材設備表", actualFinish: "", delayDays: null },
  { id: "T18", name: "公設建材選用與建築裝修粉刷規格定案", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 49, end: 63, duration: 14, type: "task", deps: "T15", deliverable: "建築裝修粉刷表", actualFinish: "", delayDays: null },
  { id: "T19", name: "08. 建築設計 (第四次)", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 63, end: 63, duration: 0, type: "milestone", deps: "T18", deliverable: "建材與裝修規格定案", actualFinish: "", delayDays: null },
  { id: "T20", name: "開圖計畫、單坪造價標準與設備規格清單", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 56, end: 70, duration: 14, type: "task", deps: "T17", deliverable: "標配選配廠牌規格表", actualFinish: "", delayDays: null },
  { id: "T20", name: "開圖計畫、單坪造價標準與設備規格清單", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 56, end: 70, duration: 14, type: "task", deps: "T17", deliverable: "機電造價分析表", actualFinish: "", delayDays: null },
  { id: "T21", name: "09. 機電工程設計 (第三次)", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 70, end: 70, duration: 0, type: "milestone", deps: "T20", deliverable: "機電設備規格與出圖計畫確認", actualFinish: "", delayDays: null },
  { id: "T22", name: "立面主題風格、燈光計畫、景觀與指標系統", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 63, end: 77, duration: 14, type: "task", deps: "T19", deliverable: "個案主題風格定位表", actualFinish: "", delayDays: null },
  { id: "T22", name: "立面主題風格、燈光計畫、景觀與指標系統", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 63, end: 77, duration: 14, type: "task", deps: "T19", deliverable: "公設項目設定表", actualFinish: "", delayDays: null },
  { id: "T22", name: "立面主題風格、燈光計畫、景觀與指標系統", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 63, end: 77, duration: 14, type: "task", deps: "T19", deliverable: "完成面淨高彩色圖", actualFinish: "", delayDays: null },
  { id: "T23", name: "10. 建築設計 (第五次)", section: "階段 3：規劃設計與工程深化", owner: "建築師", start: 77, end: 77, duration: 0, type: "milestone", deps: "T22", deliverable: "外觀立面與公設/景觀美學定案", actualFinish: "", delayDays: null },
  { id: "T24", name: "智慧建築、綠建築評估與弱電安控整合", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 70, end: 84, duration: 14, type: "task", deps: "T21", deliverable: "智慧綠建築評估檢核表", actualFinish: "", delayDays: null },
  { id: "T24", name: "智慧建築、綠建築評估與弱電安控整合", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 70, end: 84, duration: 14, type: "task", deps: "T21", deliverable: "弱電監控系統架構圖", actualFinish: "", delayDays: null },
  { id: "T25", name: "11. 機電工程設計 (第四次)", section: "階段 3：規劃設計與工程深化", owner: "機電技師", start: 84, end: 84, duration: 0, type: "milestone", deps: "T24", deliverable: "智慧建築/綠建築評估確認", actualFinish: "", delayDays: null },
  { id: "T26", name: "全案產品定位結論、造價與總銷選用表收斂", section: "階段 4：定位結論與總結收斂", owner: "設計專案", start: 84, end: 98, duration: 14, type: "task", deps: "T23, T25", deliverable: "產品定位結論總表", actualFinish: "", delayDays: null },
  { id: "T26", name: "全案產品定位結論、造價與總銷選用表收斂", section: "階段 4：定位結論與總結收斂", owner: "設計專案", start: 84, end: 98, duration: 14, type: "task", deps: "T23, T25", deliverable: "創造總銷選用表", actualFinish: "", delayDays: null },
  { id: "T27", name: "12. 建築設計 (第六次 / 定位結論綜合會議)", section: "階段 4：定位結論與總結收斂", owner: "設計專案", start: 98, end: 98, duration: 0, type: "milestone", deps: "T26", deliverable: "全案產品定位報告定案與後續請照移交", actualFinish: "", delayDays: null }
];
